spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource: 
    url: jdbc:postgresql://db.luizvzbduxbunbiswfvi.supabase.co:5432/postgres?user=postgres&password=jainfsdgroup9
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init: 
      platform: postgres
management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
